package com.example.ricardopessoa.androidgooglebooks;

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import com.example.ricardopessoa.androidgooglebooks.model.Book;
import com.example.ricardopessoa.androidgooglebooks.model.BookList;
import com.google.gson.Gson;
import java.util.ArrayList;
import java.util.List;
import org.junit.Test;

public class BookUnitTest {

  private String jsonResponse = "{\n"
      + " \"kind\": \"books#volume\",\n"
      + " \"id\": \"e74ICAAAQBAJ\",\n"
      + " \"etag\": \"ObA84I0rrBQ\",\n"
      + " \"selfLink\": \"https://www.googleapis.com/books/v1/volumes/e74ICAAAQBAJ\",\n"
      + " \"volumeInfo\": {\n"
      + "  \"title\": \"Pro Android Games\",\n"
      + "  \"subtitle\": \"L Edition\",\n"
      + "  \"authors\": [\n"
      + "   \"Massimo Nardone\",\n"
      + "   \"Vladimir Silva\"\n"
      + "  ],\n"
      + "  \"publisher\": \"Apress\",\n"
      + "  \"publishedDate\": \"2015-02-14\",\n"
      + "  \"description\": \"\\u003cp\\u003eCombining actionable, real-world source code with graphics, Pro Android Games, Third Edition shows you how to build more sophisticated and addictive Android game apps with minimum effort. Harness the power of the latest Android 5.0 SDK to bring countless legendary, action-packed PC games to the Android platform. \\u003c/p\\u003e\\u003cp\\u003eWith actionable real-world source code, this one of a kind book shows you how to build more sophisticated and addictive Android game apps, by leveraging the power of the recent advancements found in the new Android 5.0 software development kit as well as those you've counted on in earlier releases.\\u003c/p\\u003e\\u003cp\\u003eMulti-touch code gives these games and their players dynamic input and exchange ability, for a more realistic arcade game experience. Faster and better performance offers Android game players a more seamless, fun arcade experience like never before. There is also improved native C/C++ integration with Android's NDK as well, which makes coding, compiling, and converting both productive and efficient with gains in app performance.\\u003c/p\\u003e\\u003cp\\u003e\\u003c/p\\u003e\\u003cp\\u003ePro Android Games, Third Edition features the following improvements:\\u003c/p\\u003e\\u003cul\\u003e\\u003cli\\u003eUpdates to the latest version of the Android SDK, NDK, plus the latest Android Studio and Eclipse IDEs\\u003c/li\\u003e\\u003cli\\u003eGreater focus on tablets, ever changing device resolutions, and hardware specs\\u003c/li\\u003e\\u003cli\\u003eNative game development and hardware accelerated graphics\\u003c/li\\u003e\\u003cli\\u003eBigger and better real world engines, such as Quake I and II plus an oldie from the previous edition: Doom\\u003c/li\\u003e\\u003cli\\u003eCoverage of the new Android TV SDK APIs, UI, UX, multi-touch and multi-tasking features available with the Android 5.0 release\\u003c/li\\u003e\\u003cli\\u003eAdvanced techniques for improving your game playing experience including better multi-tasking, improved performance optimization, battery management and more\\u003c/li\\u003e\\u003cli\\u003eA \\\"Quake 3D\\\"-like game app case study\\u003c/li\\u003e\\u003c/ul\\u003e\\u003cp\\u003eYou’ll definitely have fun, and perhaps you’ll even make some money. Enjoy!\\u003c/p\\u003e\\u003cp\\u003eIn the last few years, Android has progressed with the debut of better fonts, new User Interface and Experience (UI/UX) APIs, tablet considerations, multi-touch capabilities, multi-tasking, faster performance, improved battery management techniques, and now the new Android TV SDK Apps for the Android game app developer repertoire.\\u003c/p\\u003e\",\n"
      + "  \"industryIdentifiers\": [\n"
      + "   {\n"
      + "    \"type\": \"ISBN_10\",\n"
      + "    \"identifier\": \"1484205871\"\n"
      + "   },\n"
      + "   {\n"
      + "    \"type\": \"ISBN_13\",\n"
      + "    \"identifier\": \"9781484205877\"\n"
      + "   }\n"
      + "  ],\n"
      + "  \"readingModes\": {\n"
      + "   \"text\": true,\n"
      + "   \"image\": true\n"
      + "  },\n"
      + "  \"pageCount\": 408,\n"
      + "  \"printedPageCount\": 395,\n"
      + "  \"dimensions\": {\n"
      + "   \"height\": \"26.00 cm\"\n"
      + "  },\n"
      + "  \"printType\": \"BOOK\",\n"
      + "  \"categories\": [\n"
      + "   \"Computers / Programming / Games\",\n"
      + "   \"Computers / Programming / General\",\n"
      + "   \"Computers / Programming Languages / General\",\n"
      + "   \"Computers / Information Technology\"\n"
      + "  ],\n"
      + "  \"maturityRating\": \"NOT_MATURE\",\n"
      + "  \"allowAnonLogging\": true,\n"
      + "  \"contentVersion\": \"0.5.4.0.preview.3\",\n"
      + "  \"panelizationSummary\": {\n"
      + "   \"containsEpubBubbles\": false,\n"
      + "   \"containsImageBubbles\": false\n"
      + "  },\n"
      + "  \"imageLinks\": {\n"
      + "   \"smallThumbnail\": \"http://books.google.com/books/content?id=e74ICAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE71GiU0ibvphytbgktZjv4-P1Q1SLIiRj7wZjLTnJOtTIDvOeftfesivB5H2EoGHnXiHPvaqhenR6q46JpX9Y2FmtFqP7eCSMfUwFIq5fHAKoHISn_YRoaMe0bxAY4sxK_aMJKmy&source=gbs_api\",\n"
      + "   \"thumbnail\": \"http://books.google.com/books/content?id=e74ICAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE73237ciHe4RhgsEPV7BjprQ0kGgt9evGY5JWwpmzAAjBav71LkHbGhhxKfNSTQ0j_E026a4jw6D5JCBZgHcWyjtiOR1hmWxqqhhZo1Ctqvd6ZYX_sNX4yJbvaX4YbDldD8z9y-k&source=gbs_api\",\n"
      + "   \"small\": \"http://books.google.com/books/content?id=e74ICAAAQBAJ&printsec=frontcover&img=1&zoom=2&edge=curl&imgtk=AFLRE70f5FuUrvP2E2w6kFbyrTwLXqC47S22R3hKUBOgWQ53k0k8SVrraaDY9WPerri-kbeXBenAHrJf9pGgzdElc0EGxBUh3oYux1g-AZJpRBbb3e-hC1fGK1UfEBNBXREC10DXQ8rM&source=gbs_api\",\n"
      + "   \"medium\": \"http://books.google.com/books/content?id=e74ICAAAQBAJ&printsec=frontcover&img=1&zoom=3&edge=curl&imgtk=AFLRE71Ja_xEzfXxOlo-yJKB3L34njJixbCxR9-eSFaCplYZuhKdZ4C7K5YawhKIFWselpD6r6tOiONfuh3Uy-Wl4X1Ya5UmQMAOGgRFI_zPP-VH8NYAa1mXRTmHhasWTnoxqCKMQC4z&source=gbs_api\",\n"
      + "   \"large\": \"http://books.google.com/books/content?id=e74ICAAAQBAJ&printsec=frontcover&img=1&zoom=4&edge=curl&imgtk=AFLRE73jUqP1dqfE-vLOGECxLxT2UhipP1qez-RSrkKgYDZ47456uCP3sfeCHD6TM5JTk9sj9RPzXeshCNdOazLiyxuLPgeHHlfs-b1mIyiktPXwOqL2AZiqx3J5xnR6VRRqHDbmanK7&source=gbs_api\",\n"
      + "   \"extraLarge\": \"http://books.google.com/books/content?id=e74ICAAAQBAJ&printsec=frontcover&img=1&zoom=6&edge=curl&imgtk=AFLRE70gglZR3wIdrEmR3Ey3x35sgQYJ8gPOCMvIzrHd4bOUcUWUUmlaSX9l4MNPxae5W-ZmJffYc8xX-2L_PYTqxE3eYXqCLxf4sLtn4ApzqzzzsKG4s2S8hrrV27VWl0DHx6qLZ9qI&source=gbs_api\"\n"
      + "  },\n"
      + "  \"language\": \"en\",\n"
      + "  \"previewLink\": \"http://books.google.ch/books?id=e74ICAAAQBAJ&hl=&source=gbs_api\",\n"
      + "  \"infoLink\": \"https://play.google.com/store/books/details?id=e74ICAAAQBAJ&source=gbs_api\",\n"
      + "  \"canonicalVolumeLink\": \"https://market.android.com/details?id=book-e74ICAAAQBAJ\"\n"
      + " },\n"
      + " \"layerInfo\": {\n"
      + "  \"layers\": [\n"
      + "   {\n"
      + "    \"layerId\": \"geo\",\n"
      + "    \"volumeAnnotationsVersion\": \"6\"\n"
      + "   }\n"
      + "  ]\n"
      + " },\n"
      + " \"saleInfo\": {\n"
      + "  \"country\": \"CH\",\n"
      + "  \"saleability\": \"FOR_SALE\",\n"
      + "  \"isEbook\": true,\n"
      + "  \"listPrice\": {\n"
      + "   \"amount\": 42.0,\n"
      + "   \"currencyCode\": \"CHF\"\n"
      + "  },\n"
      + "  \"retailPrice\": {\n"
      + "   \"amount\": 29.4,\n"
      + "   \"currencyCode\": \"CHF\"\n"
      + "  },\n"
      + "  \"buyLink\": \"https://play.google.com/store/books/details?id=e74ICAAAQBAJ&rdid=book-e74ICAAAQBAJ&rdot=1&source=gbs_api\",\n"
      + "  \"offers\": [\n"
      + "   {\n"
      + "    \"finskyOfferType\": 1,\n"
      + "    \"listPrice\": {\n"
      + "     \"amountInMicros\": 4.2E7,\n"
      + "     \"currencyCode\": \"CHF\"\n"
      + "    },\n"
      + "    \"retailPrice\": {\n"
      + "     \"amountInMicros\": 2.94E7,\n"
      + "     \"currencyCode\": \"CHF\"\n"
      + "    },\n"
      + "    \"giftable\": true\n"
      + "   }\n"
      + "  ]\n"
      + " },\n"
      + " \"accessInfo\": {\n"
      + "  \"country\": \"CH\",\n"
      + "  \"viewability\": \"PARTIAL\",\n"
      + "  \"embeddable\": true,\n"
      + "  \"publicDomain\": false,\n"
      + "  \"textToSpeechPermission\": \"ALLOWED\",\n"
      + "  \"epub\": {\n"
      + "   \"isAvailable\": true,\n"
      + "   \"acsTokenLink\": \"http://books.google.ch/books/download/Pro_Android_Games-sample-epub.acsm?id=e74ICAAAQBAJ&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api\"\n"
      + "  },\n"
      + "  \"pdf\": {\n"
      + "   \"isAvailable\": true,\n"
      + "   \"acsTokenLink\": \"http://books.google.ch/books/download/Pro_Android_Games-sample-pdf.acsm?id=e74ICAAAQBAJ&format=pdf&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api\"\n"
      + "  },\n"
      + "  \"webReaderLink\": \"http://play.google.com/books/reader?id=e74ICAAAQBAJ&hl=&printsec=frontcover&source=gbs_api\",\n"
      + "  \"accessViewStatus\": \"SAMPLE\",\n"
      + "  \"quoteSharingAllowed\": false\n"
      + " }\n"
      + "}\n";

  @Test
  public void checkParseOfBook(){

    Gson gson = new Gson(); // Or use new GsonBuilder().create();
    Book book = gson.fromJson(jsonResponse,Book.class);
    assertNotNull(book);
  }
}
