package com.example.ricardopessoa.androidgooglebooks;

import com.example.ricardopessoa.androidgooglebooks.model.Book;
import com.example.ricardopessoa.androidgooglebooks.model.BookList;
import com.google.gson.Gson;
import java.util.ArrayList;
import java.util.List;
import org.junit.Test;
import static org.junit.Assert.*;

public class BookListUnitTest {

  private String jsonResponse = "{\n"
      + " \"kind\": \"books#volumes\",\n"
      + " \"totalItems\": 596,\n"
      + " \"items\": [\n"
      + "  {\n"
      + "   \"kind\": \"books#volume\",\n"
      + "   \"id\": \"e74ICAAAQBAJ\",\n"
      + "   \"etag\": \"1/ctrpl9tvc\",\n"
      + "   \"selfLink\": \"https://www.googleapis.com/books/v1/volumes/e74ICAAAQBAJ\",\n"
      + "   \"volumeInfo\": {\n"
      + "    \"title\": \"Pro Android Games\",\n"
      + "    \"subtitle\": \"L Edition\",\n"
      + "    \"authors\": [\n"
      + "     \"Massimo Nardone\",\n"
      + "     \"Vladimir Silva\"\n"
      + "    ],\n"
      + "    \"publisher\": \"Apress\",\n"
      + "    \"publishedDate\": \"2015-02-14\",\n"
      + "    \"description\": \"Combining actionable, real-world source code with graphics, Pro Android Games, Third Edition shows you how to build more sophisticated and addictive Android game apps with minimum effort. Harness the power of the latest Android 5.0 SDK to bring countless legendary, action-packed PC games to the Android platform. With actionable real-world source code, this one of a kind book shows you how to build more sophisticated and addictive Android game apps, by leveraging the power of the recent advancements found in the new Android 5.0 software development kit as well as those you've counted on in earlier releases. Multi-touch code gives these games and their players dynamic input and exchange ability, for a more realistic arcade game experience. Faster and better performance offers Android game players a more seamless, fun arcade experience like never before. There is also improved native C/C++ integration with Android's NDK as well, which makes coding, compiling, and converting both productive and efficient with gains in app performance. Pro Android Games, Third Edition features the following improvements: Updates to the latest version of the Android SDK, NDK, plus the latest Android Studio and Eclipse IDEs Greater focus on tablets, ever changing device resolutions, and hardware specs Native game development and hardware accelerated graphics Bigger and better real world engines, such as Quake I and II plus an oldie from the previous edition: Doom Coverage of the new Android TV SDK APIs, UI, UX, multi-touch and multi-tasking features available with the Android 5.0 release Advanced techniques for improving your game playing experience including better multi-tasking, improved performance optimization, battery management and more A \\\"Quake 3D\\\"-like game app case study You’ll definitely have fun, and perhaps you’ll even make some money. Enjoy! In the last few years, Android has progressed with the debut of better fonts, new User Interface and Experience (UI/UX) APIs, tablet considerations, multi-touch capabilities, multi-tasking, faster performance, improved battery management techniques, and now the new Android TV SDK Apps for the Android game app developer repertoire.\",\n"
      + "    \"industryIdentifiers\": [\n"
      + "     {\n"
      + "      \"type\": \"ISBN_13\",\n"
      + "      \"identifier\": \"9781484205877\"\n"
      + "     },\n"
      + "     {\n"
      + "      \"type\": \"ISBN_10\",\n"
      + "      \"identifier\": \"1484205871\"\n"
      + "     }\n"
      + "    ],\n"
      + "    \"readingModes\": {\n"
      + "     \"text\": true,\n"
      + "     \"image\": true\n"
      + "    },\n"
      + "    \"pageCount\": 408,\n"
      + "    \"printType\": \"BOOK\",\n"
      + "    \"categories\": [\n"
      + "     \"Computers\"\n"
      + "    ],\n"
      + "    \"maturityRating\": \"NOT_MATURE\",\n"
      + "    \"allowAnonLogging\": true,\n"
      + "    \"contentVersion\": \"0.5.4.0.preview.3\",\n"
      + "    \"panelizationSummary\": {\n"
      + "     \"containsEpubBubbles\": false,\n"
      + "     \"containsImageBubbles\": false\n"
      + "    },\n"
      + "    \"imageLinks\": {\n"
      + "     \"smallThumbnail\": \"http://books.google.com/books/content?id=e74ICAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api\",\n"
      + "     \"thumbnail\": \"http://books.google.com/books/content?id=e74ICAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\"\n"
      + "    },\n"
      + "    \"language\": \"en\",\n"
      + "    \"previewLink\": \"http://books.google.ch/books?id=e74ICAAAQBAJ&pg=PA45&dq=android:keyes&hl=&cd=1&source=gbs_api\",\n"
      + "    \"infoLink\": \"https://play.google.com/store/books/details?id=e74ICAAAQBAJ&source=gbs_api\",\n"
      + "    \"canonicalVolumeLink\": \"https://market.android.com/details?id=book-e74ICAAAQBAJ\"\n"
      + "   },\n"
      + "   \"saleInfo\": {\n"
      + "    \"country\": \"CH\",\n"
      + "    \"saleability\": \"FOR_SALE\",\n"
      + "    \"isEbook\": true,\n"
      + "    \"listPrice\": {\n"
      + "     \"amount\": 42.0,\n"
      + "     \"currencyCode\": \"CHF\"\n"
      + "    },\n"
      + "    \"retailPrice\": {\n"
      + "     \"amount\": 29.4,\n"
      + "     \"currencyCode\": \"CHF\"\n"
      + "    },\n"
      + "    \"buyLink\": \"https://play.google.com/store/books/details?id=e74ICAAAQBAJ&rdid=book-e74ICAAAQBAJ&rdot=1&source=gbs_api\",\n"
      + "    \"offers\": [\n"
      + "     {\n"
      + "      \"finskyOfferType\": 1,\n"
      + "      \"listPrice\": {\n"
      + "       \"amountInMicros\": 4.2E7,\n"
      + "       \"currencyCode\": \"CHF\"\n"
      + "      },\n"
      + "      \"retailPrice\": {\n"
      + "       \"amountInMicros\": 2.94E7,\n"
      + "       \"currencyCode\": \"CHF\"\n"
      + "      },\n"
      + "      \"giftable\": true\n"
      + "     }\n"
      + "    ]\n"
      + "   },\n"
      + "   \"accessInfo\": {\n"
      + "    \"country\": \"CH\",\n"
      + "    \"viewability\": \"PARTIAL\",\n"
      + "    \"embeddable\": true,\n"
      + "    \"publicDomain\": false,\n"
      + "    \"textToSpeechPermission\": \"ALLOWED\",\n"
      + "    \"epub\": {\n"
      + "     \"isAvailable\": true,\n"
      + "     \"acsTokenLink\": \"http://books.google.ch/books/download/Pro_Android_Games-sample-epub.acsm?id=e74ICAAAQBAJ&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api\"\n"
      + "    },\n"
      + "    \"pdf\": {\n"
      + "     \"isAvailable\": true,\n"
      + "     \"acsTokenLink\": \"http://books.google.ch/books/download/Pro_Android_Games-sample-pdf.acsm?id=e74ICAAAQBAJ&format=pdf&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api\"\n"
      + "    },\n"
      + "    \"webReaderLink\": \"http://play.google.com/books/reader?id=e74ICAAAQBAJ&hl=&printsec=frontcover&source=gbs_api\",\n"
      + "    \"accessViewStatus\": \"SAMPLE\",\n"
      + "    \"quoteSharingAllowed\": false\n"
      + "   },\n"
      + "   \"searchInfo\": {\n"
      + "    \"textSnippet\": \"Cascading key events from Android to a native engine involves these steps: 1. \\u003cbr\\u003e\\nListening for key presses or releases from the Android activity. 2. Translating the \\u003cbr\\u003e\\n\\u003cb\\u003eAndroid keys\\u003c/b\\u003e to ASCII (or whatever format the engine uses to encode keys). 3.\"\n"
      + "   }\n"
      + "  },\n"
      + "  {\n"
      + "   \"kind\": \"books#volume\",\n"
      + "   \"id\": \"YfaqnbJy4FwC\",\n"
      + "   \"etag\": \"1N4dupAFz1c\",\n"
      + "   \"selfLink\": \"https://www.googleapis.com/books/v1/volumes/YfaqnbJy4FwC\",\n"
      + "   \"volumeInfo\": {\n"
      + "    \"title\": \"Advanced Android 4 Games\",\n"
      + "    \"authors\": [\n"
      + "     \"Vladimir Silva\"\n"
      + "    ],\n"
      + "    \"publisher\": \"Apress\",\n"
      + "    \"publishedDate\": \"2013-07-30\",\n"
      + "    \"description\": \"\\\"Wolfenstein 3D\\\"-like and \\\"Doom\\\"-like game apps are some of the classic Android games presented in the original edition of this book. Since their release, Android has progressed with the debut of Android 4.0, adding better fonts, new User Interface and Experience (UI/UX) APIs, tablet considerations, multi-touch capabilities, multi-tasking, faster performance, and much more to the Android game app development repertoire. Multi-touch code gives these games and their players dynamic input and exchange ability, for a more realistic arcade game experience. Faster and better performance offers game players a more seamless, fun arcade experience like never before on Android. There is also improved native C/C++ integration with Android's NDK as well, which makes coding, compiling, and converting both productive and efficient with gains in app performance. With actionable real-world source, Advanced Android 4 Games shows you how to build more sophisticated and addictive Android games, harnessing the power of these recent advancements. Coverage of the new UI, UX, multi-touch and multi-tasking features available with Android 4.0. Learn other techniques for improving the game playing experience including Wi-Fi tethering, better multi-tasking, new and better streaming Web video using WebM, and more. By combining the elegant object-oriented features of Java and the raw power of C, there is no limit to the types of games that you can build for the platform, such as the \\\"Quake 3D\\\"-like game app case study in this book. You'll definitely have fun, and perhaps you'll even make some money. Enjoy!\",\n"
      + "    \"industryIdentifiers\": [\n"
      + "     {\n"
      + "      \"type\": \"ISBN_13\",\n"
      + "      \"identifier\": \"9781430240600\"\n"
      + "     },\n"
      + "     {\n"
      + "      \"type\": \"ISBN_10\",\n"
      + "      \"identifier\": \"1430240601\"\n"
      + "     }\n"
      + "    ],\n"
      + "    \"readingModes\": {\n"
      + "     \"text\": true,\n"
      + "     \"image\": true\n"
      + "    },\n"
      + "    \"pageCount\": 280,\n"
      + "    \"printType\": \"BOOK\",\n"
      + "    \"categories\": [\n"
      + "     \"Computers\"\n"
      + "    ],\n"
      + "    \"maturityRating\": \"NOT_MATURE\",\n"
      + "    \"allowAnonLogging\": false,\n"
      + "    \"contentVersion\": \"1.4.3.0.preview.3\",\n"
      + "    \"panelizationSummary\": {\n"
      + "     \"containsEpubBubbles\": false,\n"
      + "     \"containsImageBubbles\": false\n"
      + "    },\n"
      + "    \"imageLinks\": {\n"
      + "     \"smallThumbnail\": \"http://books.google.com/books/content?id=YfaqnbJy4FwC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api\",\n"
      + "     \"thumbnail\": \"http://books.google.com/books/content?id=YfaqnbJy4FwC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\"\n"
      + "    },\n"
      + "    \"language\": \"en\",\n"
      + "    \"previewLink\": \"http://books.google.ch/books?id=YfaqnbJy4FwC&pg=PA46&dq=android:keyes&hl=&cd=2&source=gbs_api\",\n"
      + "    \"infoLink\": \"https://play.google.com/store/books/details?id=YfaqnbJy4FwC&source=gbs_api\",\n"
      + "    \"canonicalVolumeLink\": \"https://market.android.com/details?id=book-YfaqnbJy4FwC\"\n"
      + "   },\n"
      + "   \"saleInfo\": {\n"
      + "    \"country\": \"CH\",\n"
      + "    \"saleability\": \"FOR_SALE\",\n"
      + "    \"isEbook\": true,\n"
      + "    \"listPrice\": {\n"
      + "     \"amount\": 53.5,\n"
      + "     \"currencyCode\": \"CHF\"\n"
      + "    },\n"
      + "    \"retailPrice\": {\n"
      + "     \"amount\": 37.45,\n"
      + "     \"currencyCode\": \"CHF\"\n"
      + "    },\n"
      + "    \"buyLink\": \"https://play.google.com/store/books/details?id=YfaqnbJy4FwC&rdid=book-YfaqnbJy4FwC&rdot=1&source=gbs_api\",\n"
      + "    \"offers\": [\n"
      + "     {\n"
      + "      \"finskyOfferType\": 1,\n"
      + "      \"listPrice\": {\n"
      + "       \"amountInMicros\": 5.35E7,\n"
      + "       \"currencyCode\": \"CHF\"\n"
      + "      },\n"
      + "      \"retailPrice\": {\n"
      + "       \"amountInMicros\": 3.745E7,\n"
      + "       \"currencyCode\": \"CHF\"\n"
      + "      },\n"
      + "      \"giftable\": true\n"
      + "     }\n"
      + "    ]\n"
      + "   },\n"
      + "   \"accessInfo\": {\n"
      + "    \"country\": \"CH\",\n"
      + "    \"viewability\": \"PARTIAL\",\n"
      + "    \"embeddable\": true,\n"
      + "    \"publicDomain\": false,\n"
      + "    \"textToSpeechPermission\": \"ALLOWED\",\n"
      + "    \"epub\": {\n"
      + "     \"isAvailable\": true,\n"
      + "     \"acsTokenLink\": \"http://books.google.ch/books/download/Advanced_Android_4_Games-sample-epub.acsm?id=YfaqnbJy4FwC&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api\"\n"
      + "    },\n"
      + "    \"pdf\": {\n"
      + "     \"isAvailable\": true,\n"
      + "     \"acsTokenLink\": \"http://books.google.ch/books/download/Advanced_Android_4_Games-sample-pdf.acsm?id=YfaqnbJy4FwC&format=pdf&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api\"\n"
      + "    },\n"
      + "    \"webReaderLink\": \"http://play.google.com/books/reader?id=YfaqnbJy4FwC&hl=&printsec=frontcover&source=gbs_api\",\n"
      + "    \"accessViewStatus\": \"SAMPLE\",\n"
      + "    \"quoteSharingAllowed\": false\n"
      + "   },\n"
      + "   \"searchInfo\": {\n"
      + "    \"textSnippet\": \"Cascading key events from Android to a native engine involves the following \\u003cbr\\u003e\\nsteps: 1. Listening for key presses or releases from the Android activity. 2. \\u003cbr\\u003e\\nTranslating the \\u003cb\\u003eandroid keys\\u003c/b\\u003e to ASCII (or whatever format the engine uses to \\u003cbr\\u003e\\nencode keys).\"\n"
      + "   }\n"
      + "  },\n"
      + "  {\n"
      + "   \"kind\": \"books#volume\",\n"
      + "   \"id\": \"XLAJXwcCRz0C\",\n"
      + "   \"etag\": \"kjrf6vH0Rjg\",\n"
      + "   \"selfLink\": \"https://www.googleapis.com/books/v1/volumes/XLAJXwcCRz0C\",\n"
      + "   \"volumeInfo\": {\n"
      + "    \"title\": \"Pro Android 2\",\n"
      + "    \"authors\": [\n"
      + "     \"Sayed Hashimi\",\n"
      + "     \"Satya Komatineni\",\n"
      + "     \"Dave MacLean\"\n"
      + "    ],\n"
      + "    \"publisher\": \"Apress\",\n"
      + "    \"publishedDate\": \"2010-08-05\",\n"
      + "    \"description\": \"Pro Android 2 shows how to build real-world and fun mobile applications using Google's latest Android software development kit. This new edition is updated for Android 2, covering everything from the fundamentals of building applications for embedded devices to advanced concepts such as custom 3D components, OpenGL, and touchscreens including gestures. While other Android development guides simply discuss topics, Pro Android 2 offers the combination of expert insight and real sample applications that work. Discover the design and architecture of the Android SDK through practical examples, and how to build mobile applications using the Android SDK. Explore and use the Android APIs, including those for media and Wi-Fi. Learn about Android 2's integrated local and web search, handwriting gesture UI, Google Translate, and text-to-speech features. Pro Android 2 dives deep, providing you with all the knowledge and techniques you need to build mobile applications ranging from games to Google apps, including add-ons to Google Docs. You'll be able to extend and run the new Google Chrome APIs on the G1, the G2, and other next-generation Google phones and Android-enabled devices.\",\n"
      + "    \"industryIdentifiers\": [\n"
      + "     {\n"
      + "      \"type\": \"ISBN_13\",\n"
      + "      \"identifier\": \"9781430226604\"\n"
      + "     },\n"
      + "     {\n"
      + "      \"type\": \"ISBN_10\",\n"
      + "      \"identifier\": \"1430226609\"\n"
      + "     }\n"
      + "    ],\n"
      + "    \"readingModes\": {\n"
      + "     \"text\": true,\n"
      + "     \"image\": true\n"
      + "    },\n"
      + "    \"pageCount\": 736,\n"
      + "    \"printType\": \"BOOK\",\n"
      + "    \"categories\": [\n"
      + "     \"Computers\"\n"
      + "    ],\n"
      + "    \"maturityRating\": \"NOT_MATURE\",\n"
      + "    \"allowAnonLogging\": false,\n"
      + "    \"contentVersion\": \"1.6.4.0.preview.3\",\n"
      + "    \"panelizationSummary\": {\n"
      + "     \"containsEpubBubbles\": false,\n"
      + "     \"containsImageBubbles\": false\n"
      + "    },\n"
      + "    \"imageLinks\": {\n"
      + "     \"smallThumbnail\": \"http://books.google.com/books/content?id=XLAJXwcCRz0C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api\",\n"
      + "     \"thumbnail\": \"http://books.google.com/books/content?id=XLAJXwcCRz0C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\"\n"
      + "    },\n"
      + "    \"language\": \"en\",\n"
      + "    \"previewLink\": \"http://books.google.ch/books?id=XLAJXwcCRz0C&pg=PA557&dq=android:keyes&hl=&cd=3&source=gbs_api\",\n"
      + "    \"infoLink\": \"https://play.google.com/store/books/details?id=XLAJXwcCRz0C&source=gbs_api\",\n"
      + "    \"canonicalVolumeLink\": \"https://market.android.com/details?id=book-XLAJXwcCRz0C\"\n"
      + "   },\n"
      + "   \"saleInfo\": {\n"
      + "    \"country\": \"CH\",\n"
      + "    \"saleability\": \"FOR_SALE\",\n"
      + "    \"isEbook\": true,\n"
      + "    \"listPrice\": {\n"
      + "     \"amount\": 49.5,\n"
      + "     \"currencyCode\": \"CHF\"\n"
      + "    },\n"
      + "    \"retailPrice\": {\n"
      + "     \"amount\": 34.65,\n"
      + "     \"currencyCode\": \"CHF\"\n"
      + "    },\n"
      + "    \"buyLink\": \"https://play.google.com/store/books/details?id=XLAJXwcCRz0C&rdid=book-XLAJXwcCRz0C&rdot=1&source=gbs_api\",\n"
      + "    \"offers\": [\n"
      + "     {\n"
      + "      \"finskyOfferType\": 1,\n"
      + "      \"listPrice\": {\n"
      + "       \"amountInMicros\": 4.95E7,\n"
      + "       \"currencyCode\": \"CHF\"\n"
      + "      },\n"
      + "      \"retailPrice\": {\n"
      + "       \"amountInMicros\": 3.465E7,\n"
      + "       \"currencyCode\": \"CHF\"\n"
      + "      },\n"
      + "      \"giftable\": true\n"
      + "     }\n"
      + "    ]\n"
      + "   },\n"
      + "   \"accessInfo\": {\n"
      + "    \"country\": \"CH\",\n"
      + "    \"viewability\": \"PARTIAL\",\n"
      + "    \"embeddable\": true,\n"
      + "    \"publicDomain\": false,\n"
      + "    \"textToSpeechPermission\": \"ALLOWED\",\n"
      + "    \"epub\": {\n"
      + "     \"isAvailable\": true,\n"
      + "     \"acsTokenLink\": \"http://books.google.ch/books/download/Pro_Android_2-sample-epub.acsm?id=XLAJXwcCRz0C&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api\"\n"
      + "    },\n"
      + "    \"pdf\": {\n"
      + "     \"isAvailable\": true,\n"
      + "     \"acsTokenLink\": \"http://books.google.ch/books/download/Pro_Android_2-sample-pdf.acsm?id=XLAJXwcCRz0C&format=pdf&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api\"\n"
      + "    },\n"
      + "    \"webReaderLink\": \"http://play.google.com/books/reader?id=XLAJXwcCRz0C&hl=&printsec=frontcover&source=gbs_api\",\n"
      + "    \"accessViewStatus\": \"SAMPLE\",\n"
      + "    \"quoteSharingAllowed\": false\n"
      + "   },\n"
      + "   \"searchInfo\": {\n"
      + "    \"textSnippet\": \"\\u003cb\\u003eKeys\\u003c/b\\u003e. in. \\u003cb\\u003eAndroid\\u003c/b\\u003e. Search. So far we&#39;ve shown a number of ways to invoke search\\u003cbr\\u003e\\n: The search icon available in the QSB The search key that is part of a set of \\u003cbr\\u003e\\naction \\u003cb\\u003ekeys\\u003c/b\\u003e (shown on the right side of Figure 14–1) An explicit icon or button that \\u003cbr\\u003e\\nis&nbsp;...\"\n"
      + "   }\n"
      + "  },\n"
      + "  {\n"
      + "   \"kind\": \"books#volume\",\n"
      + "   \"id\": \"tOSNBQAAQBAJ\",\n"
      + "   \"etag\": \"OSdAF1SRVwU\",\n"
      + "   \"selfLink\": \"https://www.googleapis.com/books/v1/volumes/tOSNBQAAQBAJ\",\n"
      + "   \"volumeInfo\": {\n"
      + "    \"title\": \"Bulletproof Android\",\n"
      + "    \"subtitle\": \"Practical Advice for Building Secure Apps\",\n"
      + "    \"authors\": [\n"
      + "     \"Godfrey Nolan\"\n"
      + "    ],\n"
      + "    \"publisher\": \"Addison-Wesley Professional\",\n"
      + "    \"publishedDate\": \"2014-11-18\",\n"
      + "    \"description\": \"Battle-Tested Best Practices for Securing Android Apps throughout the Development Lifecycle Android’s immense popularity has made it today’s #1 target for attack: high-profile victims include eHarmony, Facebook, and Delta Airlines, just to name a few. Today, every Android app needs to resist aggressive attacks and protect data, and in Bulletproof Android™, Godfrey Nolan shows you how. Unlike “black hat/gray hat” books, which focus on breaking code, this guide brings together complete best practices for hardening code throughout the entire development lifecycle. Using detailed examples from hundreds of apps he has personally audited, Nolan identifies common “anti-patterns” that expose apps to attack, and then demonstrates more secure solutions. Nolan covers authentication, networking, databases, server attacks, libraries, hardware, and more. He illuminates each technique with code examples, offering expert advice on implementation and trade-offs. Each topic is supported with a complete sample app, which demonstrates real security problems and solutions. Learn how to Apply core practices for securing the platform Protect code, algorithms, and business rules from reverse engineering Eliminate hardcoding of keys, APIs, and other static data Eradicate extraneous data from production APKs Overcome the unique challenges of mobile authentication and login Transmit information securely using SSL Prevent man-in-the-middle attacks Safely store data in SQLite databases Prevent attacks against web servers and services Avoid side-channel data leakage through third-party libraries Secure APKs running on diverse devices and Android versions Achieve HIPAA or FIPS compliance Harden devices with encryption, SELinux, Knox, and MDM Preview emerging attacks and countermeasures This guide is a perfect complement to Nolan’s Android™ Security Essentials LiveLessons (video training; ISBN-13: 978-0-13-382904-4) and reflects new risks that have been identified since the LiveLessons were released.\",\n"
      + "    \"industryIdentifiers\": [\n"
      + "     {\n"
      + "      \"type\": \"ISBN_13\",\n"
      + "      \"identifier\": \"9780133995084\"\n"
      + "     },\n"
      + "     {\n"
      + "      \"type\": \"ISBN_10\",\n"
      + "      \"identifier\": \"0133995089\"\n"
      + "     }\n"
      + "    ],\n"
      + "    \"readingModes\": {\n"
      + "     \"text\": true,\n"
      + "     \"image\": true\n"
      + "    },\n"
      + "    \"pageCount\": 240,\n"
      + "    \"printType\": \"BOOK\",\n"
      + "    \"categories\": [\n"
      + "     \"Computers\"\n"
      + "    ],\n"
      + "    \"maturityRating\": \"NOT_MATURE\",\n"
      + "    \"allowAnonLogging\": true,\n"
      + "    \"contentVersion\": \"2.3.2.0.preview.3\",\n"
      + "    \"panelizationSummary\": {\n"
      + "     \"containsEpubBubbles\": false,\n"
      + "     \"containsImageBubbles\": false\n"
      + "    },\n"
      + "    \"imageLinks\": {\n"
      + "     \"smallThumbnail\": \"http://books.google.com/books/content?id=tOSNBQAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api\",\n"
      + "     \"thumbnail\": \"http://books.google.com/books/content?id=tOSNBQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\"\n"
      + "    },\n"
      + "    \"language\": \"en\",\n"
      + "    \"previewLink\": \"http://books.google.ch/books?id=tOSNBQAAQBAJ&pg=PA124&dq=android:keyes&hl=&cd=4&source=gbs_api\",\n"
      + "    \"infoLink\": \"https://play.google.com/store/books/details?id=tOSNBQAAQBAJ&source=gbs_api\",\n"
      + "    \"canonicalVolumeLink\": \"https://market.android.com/details?id=book-tOSNBQAAQBAJ\"\n"
      + "   },\n"
      + "   \"saleInfo\": {\n"
      + "    \"country\": \"CH\",\n"
      + "    \"saleability\": \"FOR_SALE\",\n"
      + "    \"isEbook\": true,\n"
      + "    \"listPrice\": {\n"
      + "     \"amount\": 24.05,\n"
      + "     \"currencyCode\": \"CHF\"\n"
      + "    },\n"
      + "    \"retailPrice\": {\n"
      + "     \"amount\": 16.84,\n"
      + "     \"currencyCode\": \"CHF\"\n"
      + "    },\n"
      + "    \"buyLink\": \"https://play.google.com/store/books/details?id=tOSNBQAAQBAJ&rdid=book-tOSNBQAAQBAJ&rdot=1&source=gbs_api\",\n"
      + "    \"offers\": [\n"
      + "     {\n"
      + "      \"finskyOfferType\": 1,\n"
      + "      \"listPrice\": {\n"
      + "       \"amountInMicros\": 2.405E7,\n"
      + "       \"currencyCode\": \"CHF\"\n"
      + "      },\n"
      + "      \"retailPrice\": {\n"
      + "       \"amountInMicros\": 1.684E7,\n"
      + "       \"currencyCode\": \"CHF\"\n"
      + "      },\n"
      + "      \"giftable\": true\n"
      + "     }\n"
      + "    ]\n"
      + "   },\n"
      + "   \"accessInfo\": {\n"
      + "    \"country\": \"CH\",\n"
      + "    \"viewability\": \"PARTIAL\",\n"
      + "    \"embeddable\": true,\n"
      + "    \"publicDomain\": false,\n"
      + "    \"textToSpeechPermission\": \"ALLOWED_FOR_ACCESSIBILITY\",\n"
      + "    \"epub\": {\n"
      + "     \"isAvailable\": false\n"
      + "    },\n"
      + "    \"pdf\": {\n"
      + "     \"isAvailable\": false\n"
      + "    },\n"
      + "    \"webReaderLink\": \"http://play.google.com/books/reader?id=tOSNBQAAQBAJ&hl=&printsec=frontcover&source=gbs_api\",\n"
      + "    \"accessViewStatus\": \"SAMPLE\",\n"
      + "    \"quoteSharingAllowed\": false\n"
      + "   },\n"
      + "   \"searchInfo\": {\n"
      + "    \"textSnippet\": \"It takes the device&#39;s unique \\u003cb\\u003eAndroid\\u003c/b\\u003e ID and the Device ID (assuming it&#39;s not a \\u003cbr\\u003e\\ntablet) as well as a whole array of phone information. All of this information is ... \\u003cbr\\u003e\\nListing 5-7 Device-specific \\u003cb\\u003ekeys\\u003c/b\\u003e android_id = Secure.getString(getBaseContext().\"\n"
      + "   }\n"
      + "  },\n"
      + "  {\n"
      + "   \"kind\": \"books#volume\",\n"
      + "   \"id\": \"rLqJNQ3_hpsC\",\n"
      + "   \"etag\": \"g0owzwIOXLw\",\n"
      + "   \"selfLink\": \"https://www.googleapis.com/books/v1/volumes/rLqJNQ3_hpsC\",\n"
      + "   \"volumeInfo\": {\n"
      + "    \"title\": \"Beginning Smartphone Web Development\",\n"
      + "    \"subtitle\": \"Building JavaScript, CSS, HTML and Ajax-based Applications for iPhone, Android, Palm Pre, BlackBerry, Windows Mobile and Nokia S60\",\n"
      + "    \"authors\": [\n"
      + "     \"Gail Frederick\",\n"
      + "     \"Rajesh Lal\"\n"
      + "    ],\n"
      + "    \"publisher\": \"Apress\",\n"
      + "    \"publishedDate\": \"2010-04-15\",\n"
      + "    \"description\": \"Today’s Web 2.0 applications (think Facebook and Twitter) go far beyond the confines of the desktop and are widely used on mobile devices. The mobile Web has become incredibly popular given the success of the iPhone and BlackBerry, the importance of Windows Mobile, and the emergence of Palm Pre (and its webOS platform). At Apress, we are fortunate to have Gail Frederick of the well-known training site Learn the Mobile Web offer her expert advice in Beginning Smartphone Web Development. In this book, Gail teaches the web standards and fundamentals specific to smartphones and other feature-driven mobile phones and devices. Shows you how to build interactive mobile web sites using web technologies optimized for browsers in smartphones Details markup fundamentals, design principles, content adaptation, usability, and interoperability Explores cross-platform standards and best practices for the mobile Web authored by the W3C, dotMobi, and similar organizations Dives deeps into the feature sets of the most popular mobile browsers, including WebKit, Chrome, Palm Pre webOS, Pocket IE, Opera Mobile, and Skyfire By the end of this book, you’ll have the training, tools, and techniques for creating robust mobile web experiences on any of these platforms for your favorite smartphone or other mobile device.\",\n"
      + "    \"industryIdentifiers\": [\n"
      + "     {\n"
      + "      \"type\": \"ISBN_13\",\n"
      + "      \"identifier\": \"9781430226215\"\n"
      + "     },\n"
      + "     {\n"
      + "      \"type\": \"ISBN_10\",\n"
      + "      \"identifier\": \"1430226218\"\n"
      + "     }\n"
      + "    ],\n"
      + "    \"readingModes\": {\n"
      + "     \"text\": true,\n"
      + "     \"image\": true\n"
      + "    },\n"
      + "    \"pageCount\": 368,\n"
      + "    \"printType\": \"BOOK\",\n"
      + "    \"categories\": [\n"
      + "     \"Computers\"\n"
      + "    ],\n"
      + "    \"maturityRating\": \"NOT_MATURE\",\n"
      + "    \"allowAnonLogging\": false,\n"
      + "    \"contentVersion\": \"1.7.5.0.preview.3\",\n"
      + "    \"panelizationSummary\": {\n"
      + "     \"containsEpubBubbles\": false,\n"
      + "     \"containsImageBubbles\": false\n"
      + "    },\n"
      + "    \"imageLinks\": {\n"
      + "     \"smallThumbnail\": \"http://books.google.com/books/content?id=rLqJNQ3_hpsC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api\",\n"
      + "     \"thumbnail\": \"http://books.google.com/books/content?id=rLqJNQ3_hpsC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\"\n"
      + "    },\n"
      + "    \"language\": \"en\",\n"
      + "    \"previewLink\": \"http://books.google.ch/books?id=rLqJNQ3_hpsC&pg=PA58&dq=android:keyes&hl=&cd=5&source=gbs_api\",\n"
      + "    \"infoLink\": \"https://play.google.com/store/books/details?id=rLqJNQ3_hpsC&source=gbs_api\",\n"
      + "    \"canonicalVolumeLink\": \"https://market.android.com/details?id=book-rLqJNQ3_hpsC\"\n"
      + "   },\n"
      + "   \"saleInfo\": {\n"
      + "    \"country\": \"CH\",\n"
      + "    \"saleability\": \"FOR_SALE\",\n"
      + "    \"isEbook\": true,\n"
      + "    \"listPrice\": {\n"
      + "     \"amount\": 45.5,\n"
      + "     \"currencyCode\": \"CHF\"\n"
      + "    },\n"
      + "    \"retailPrice\": {\n"
      + "     \"amount\": 31.85,\n"
      + "     \"currencyCode\": \"CHF\"\n"
      + "    },\n"
      + "    \"buyLink\": \"https://play.google.com/store/books/details?id=rLqJNQ3_hpsC&rdid=book-rLqJNQ3_hpsC&rdot=1&source=gbs_api\",\n"
      + "    \"offers\": [\n"
      + "     {\n"
      + "      \"finskyOfferType\": 1,\n"
      + "      \"listPrice\": {\n"
      + "       \"amountInMicros\": 4.55E7,\n"
      + "       \"currencyCode\": \"CHF\"\n"
      + "      },\n"
      + "      \"retailPrice\": {\n"
      + "       \"amountInMicros\": 3.185E7,\n"
      + "       \"currencyCode\": \"CHF\"\n"
      + "      },\n"
      + "      \"giftable\": true\n"
      + "     }\n"
      + "    ]\n"
      + "   },\n"
      + "   \"accessInfo\": {\n"
      + "    \"country\": \"CH\",\n"
      + "    \"viewability\": \"PARTIAL\",\n"
      + "    \"embeddable\": true,\n"
      + "    \"publicDomain\": false,\n"
      + "    \"textToSpeechPermission\": \"ALLOWED\",\n"
      + "    \"epub\": {\n"
      + "     \"isAvailable\": true,\n"
      + "     \"acsTokenLink\": \"http://books.google.ch/books/download/Beginning_Smartphone_Web_Development-sample-epub.acsm?id=rLqJNQ3_hpsC&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api\"\n"
      + "    },\n"
      + "    \"pdf\": {\n"
      + "     \"isAvailable\": true,\n"
      + "     \"acsTokenLink\": \"http://books.google.ch/books/download/Beginning_Smartphone_Web_Development-sample-pdf.acsm?id=rLqJNQ3_hpsC&format=pdf&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api\"\n"
      + "    },\n"
      + "    \"webReaderLink\": \"http://play.google.com/books/reader?id=rLqJNQ3_hpsC&hl=&printsec=frontcover&source=gbs_api\",\n"
      + "    \"accessViewStatus\": \"SAMPLE\",\n"
      + "    \"quoteSharingAllowed\": false\n"
      + "   },\n"
      + "   \"searchInfo\": {\n"
      + "    \"textSnippet\": \"Building JavaScript, CSS, HTML and Ajax-based Applications for iPhone, \\u003cbr\\u003e\\n\\u003cb\\u003eAndroid\\u003c/b\\u003e, Palm Pre, BlackBerry, Windows Mobile and Nokia S60 Gail Frederick, \\u003cbr\\u003e\\nRajesh Lal. &lt;div&gt;1. Ka href=&quot;/&quot; accesskey=&quot;1&quot;&gt;Home&amp;/ax/div&gt; Access \\u003cb\\u003ekeys\\u003c/b\\u003e are&nbsp;...\"\n"
      + "   }\n"
      + "  },\n"
      + "  {\n"
      + "   \"kind\": \"books#volume\",\n"
      + "   \"id\": \"cU3l9z0tTa4C\",\n"
      + "   \"etag\": \"K94+8Cl9tRI\",\n"
      + "   \"selfLink\": \"https://www.googleapis.com/books/v1/volumes/cU3l9z0tTa4C\",\n"
      + "   \"volumeInfo\": {\n"
      + "    \"title\": \"Pro Android 3\",\n"
      + "    \"authors\": [\n"
      + "     \"Sayed Hashimi\",\n"
      + "     \"Satya Komatineni\",\n"
      + "     \"Dave MacLean\"\n"
      + "    ],\n"
      + "    \"publisher\": \"Apress\",\n"
      + "    \"publishedDate\": \"2011-08-19\",\n"
      + "    \"description\": \"Pro Android 3 starts with the basics, giving you a firm foundation in Android development. It then builds on this foundation to teach you how to build real-world and fun mobile applications using the new Android 3.0 SDK. This book covers advanced concepts in detail including maps, geocoding, services, live folders, drag and drop, touchscreens, and the new Android 3.0 features: fragments and ActionBar. Pro Android 3 is uniquely comprehensive: it covers sensors, text to speech, OpenGL, live widgets, search, and the audio and video APIs. Using the code-heavy tutorials and expert advice, you'll quickly be able to build cool mobile apps and run them on dozens of Android-based smartphones. You'll explore and use the Android APIs, including those for media, sensors, and long-running services. And you'll check out what's new with Android 3.0, including the improved UI across all Android platforms, drag and drop, fragment dialogs, and more, giving you the knowledge to create stunning, cutting-edge apps, while keeping you agile enough to respond to changes in the future.\",\n"
      + "    \"industryIdentifiers\": [\n"
      + "     {\n"
      + "      \"type\": \"ISBN_13\",\n"
      + "      \"identifier\": \"9781430232230\"\n"
      + "     },\n"
      + "     {\n"
      + "      \"type\": \"ISBN_10\",\n"
      + "      \"identifier\": \"1430232234\"\n"
      + "     }\n"
      + "    ],\n"
      + "    \"readingModes\": {\n"
      + "     \"text\": true,\n"
      + "     \"image\": true\n"
      + "    },\n"
      + "    \"pageCount\": 1200,\n"
      + "    \"printType\": \"BOOK\",\n"
      + "    \"categories\": [\n"
      + "     \"Computers\"\n"
      + "    ],\n"
      + "    \"maturityRating\": \"NOT_MATURE\",\n"
      + "    \"allowAnonLogging\": false,\n"
      + "    \"contentVersion\": \"1.5.4.0.preview.3\",\n"
      + "    \"panelizationSummary\": {\n"
      + "     \"containsEpubBubbles\": false,\n"
      + "     \"containsImageBubbles\": false\n"
      + "    },\n"
      + "    \"imageLinks\": {\n"
      + "     \"smallThumbnail\": \"http://books.google.com/books/content?id=cU3l9z0tTa4C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api\",\n"
      + "     \"thumbnail\": \"http://books.google.com/books/content?id=cU3l9z0tTa4C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\"\n"
      + "    },\n"
      + "    \"language\": \"en\",\n"
      + "    \"previewLink\": \"http://books.google.ch/books?id=cU3l9z0tTa4C&pg=PR14&dq=android:keyes&hl=&cd=6&source=gbs_api\",\n"
      + "    \"infoLink\": \"https://play.google.com/store/books/details?id=cU3l9z0tTa4C&source=gbs_api\",\n"
      + "    \"canonicalVolumeLink\": \"https://market.android.com/details?id=book-cU3l9z0tTa4C\"\n"
      + "   },\n"
      + "   \"saleInfo\": {\n"
      + "    \"country\": \"CH\",\n"
      + "    \"saleability\": \"FOR_SALE\",\n"
      + "    \"isEbook\": true,\n"
      + "    \"listPrice\": {\n"
      + "     \"amount\": 57.5,\n"
      + "     \"currencyCode\": \"CHF\"\n"
      + "    },\n"
      + "    \"retailPrice\": {\n"
      + "     \"amount\": 40.25,\n"
      + "     \"currencyCode\": \"CHF\"\n"
      + "    },\n"
      + "    \"buyLink\": \"https://play.google.com/store/books/details?id=cU3l9z0tTa4C&rdid=book-cU3l9z0tTa4C&rdot=1&source=gbs_api\",\n"
      + "    \"offers\": [\n"
      + "     {\n"
      + "      \"finskyOfferType\": 1,\n"
      + "      \"listPrice\": {\n"
      + "       \"amountInMicros\": 5.75E7,\n"
      + "       \"currencyCode\": \"CHF\"\n"
      + "      },\n"
      + "      \"retailPrice\": {\n"
      + "       \"amountInMicros\": 4.025E7,\n"
      + "       \"currencyCode\": \"CHF\"\n"
      + "      },\n"
      + "      \"giftable\": true\n"
      + "     }\n"
      + "    ]\n"
      + "   },\n"
      + "   \"accessInfo\": {\n"
      + "    \"country\": \"CH\",\n"
      + "    \"viewability\": \"PARTIAL\",\n"
      + "    \"embeddable\": true,\n"
      + "    \"publicDomain\": false,\n"
      + "    \"textToSpeechPermission\": \"ALLOWED\",\n"
      + "    \"epub\": {\n"
      + "     \"isAvailable\": true,\n"
      + "     \"acsTokenLink\": \"http://books.google.ch/books/download/Pro_Android_3-sample-epub.acsm?id=cU3l9z0tTa4C&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api\"\n"
      + "    },\n"
      + "    \"pdf\": {\n"
      + "     \"isAvailable\": true,\n"
      + "     \"acsTokenLink\": \"http://books.google.ch/books/download/Pro_Android_3-sample-pdf.acsm?id=cU3l9z0tTa4C&format=pdf&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api\"\n"
      + "    },\n"
      + "    \"webReaderLink\": \"http://play.google.com/books/reader?id=cU3l9z0tTa4C&hl=&printsec=frontcover&source=gbs_api\",\n"
      + "    \"accessViewStatus\": \"SAMPLE\",\n"
      + "    \"quoteSharingAllowed\": false\n"
      + "   },\n"
      + "   \"searchInfo\": {\n"
      + "    \"textSnippet\": \"814 Using Action \\u003cb\\u003eKeys\\u003c/b\\u003e and Application-Specific Search Data.....................................\\u003cbr\\u003e\\n.............................................. 818 Using Action \\u003cb\\u003eKeys\\u003c/b\\u003e in \\u003cb\\u003eAndroid\\u003c/b\\u003e Search. ... 825 The \\u003cbr\\u003e\\nBasics of Text-to-Speech Capabilities in \\u003cb\\u003eAndroid\\u003c/b\\u003e.\"\n"
      + "   }\n"
      + "  },\n"
      + "  {\n"
      + "   \"kind\": \"books#volume\",\n"
      + "   \"id\": \"AKbNBgAAQBAJ\",\n"
      + "   \"etag\": \"GL0xBETZbr8\",\n"
      + "   \"selfLink\": \"https://www.googleapis.com/books/v1/volumes/AKbNBgAAQBAJ\",\n"
      + "   \"volumeInfo\": {\n"
      + "    \"title\": \"Exploring SE for Android\",\n"
      + "    \"authors\": [\n"
      + "     \"William Confer\",\n"
      + "     \"William Roberts\"\n"
      + "    ],\n"
      + "    \"publisher\": \"Packt Publishing Ltd\",\n"
      + "    \"publishedDate\": \"2015-02-24\",\n"
      + "    \"description\": \"This book is intended for developers and engineers with some familiarity of operating system concepts as implemented by Linux. A basic background in C code would be helpful. Their positions range from hobbyists wanting to secure their Android powered creations to OEM engineers building handsets to engineers of emerging areas where Android is seeing growth.\",\n"
      + "    \"industryIdentifiers\": [\n"
      + "     {\n"
      + "      \"type\": \"ISBN_13\",\n"
      + "      \"identifier\": \"9781784393892\"\n"
      + "     },\n"
      + "     {\n"
      + "      \"type\": \"ISBN_10\",\n"
      + "      \"identifier\": \"1784393894\"\n"
      + "     }\n"
      + "    ],\n"
      + "    \"readingModes\": {\n"
      + "     \"text\": true,\n"
      + "     \"image\": true\n"
      + "    },\n"
      + "    \"pageCount\": 214,\n"
      + "    \"printType\": \"BOOK\",\n"
      + "    \"categories\": [\n"
      + "     \"Computers\"\n"
      + "    ],\n"
      + "    \"maturityRating\": \"NOT_MATURE\",\n"
      + "    \"allowAnonLogging\": true,\n"
      + "    \"contentVersion\": \"2.2.2.0.preview.3\",\n"
      + "    \"panelizationSummary\": {\n"
      + "     \"containsEpubBubbles\": false,\n"
      + "     \"containsImageBubbles\": false\n"
      + "    },\n"
      + "    \"imageLinks\": {\n"
      + "     \"smallThumbnail\": \"http://books.google.com/books/content?id=AKbNBgAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api\",\n"
      + "     \"thumbnail\": \"http://books.google.com/books/content?id=AKbNBgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\"\n"
      + "    },\n"
      + "    \"language\": \"en\",\n"
      + "    \"previewLink\": \"http://books.google.ch/books?id=AKbNBgAAQBAJ&pg=PA139&dq=android:keyes&hl=&cd=7&source=gbs_api\",\n"
      + "    \"infoLink\": \"https://play.google.com/store/books/details?id=AKbNBgAAQBAJ&source=gbs_api\",\n"
      + "    \"canonicalVolumeLink\": \"https://market.android.com/details?id=book-AKbNBgAAQBAJ\"\n"
      + "   },\n"
      + "   \"saleInfo\": {\n"
      + "    \"country\": \"CH\",\n"
      + "    \"saleability\": \"FOR_SALE\",\n"
      + "    \"isEbook\": true,\n"
      + "    \"listPrice\": {\n"
      + "     \"amount\": 24.37,\n"
      + "     \"currencyCode\": \"CHF\"\n"
      + "    },\n"
      + "    \"retailPrice\": {\n"
      + "     \"amount\": 17.06,\n"
      + "     \"currencyCode\": \"CHF\"\n"
      + "    },\n"
      + "    \"buyLink\": \"https://play.google.com/store/books/details?id=AKbNBgAAQBAJ&rdid=book-AKbNBgAAQBAJ&rdot=1&source=gbs_api\",\n"
      + "    \"offers\": [\n"
      + "     {\n"
      + "      \"finskyOfferType\": 1,\n"
      + "      \"listPrice\": {\n"
      + "       \"amountInMicros\": 2.437E7,\n"
      + "       \"currencyCode\": \"CHF\"\n"
      + "      },\n"
      + "      \"retailPrice\": {\n"
      + "       \"amountInMicros\": 1.706E7,\n"
      + "       \"currencyCode\": \"CHF\"\n"
      + "      },\n"
      + "      \"giftable\": true\n"
      + "     }\n"
      + "    ]\n"
      + "   },\n"
      + "   \"accessInfo\": {\n"
      + "    \"country\": \"CH\",\n"
      + "    \"viewability\": \"PARTIAL\",\n"
      + "    \"embeddable\": true,\n"
      + "    \"publicDomain\": false,\n"
      + "    \"textToSpeechPermission\": \"ALLOWED\",\n"
      + "    \"epub\": {\n"
      + "     \"isAvailable\": true\n"
      + "    },\n"
      + "    \"pdf\": {\n"
      + "     \"isAvailable\": true\n"
      + "    },\n"
      + "    \"webReaderLink\": \"http://play.google.com/books/reader?id=AKbNBgAAQBAJ&hl=&printsec=frontcover&source=gbs_api\",\n"
      + "    \"accessViewStatus\": \"SAMPLE\",\n"
      + "    \"quoteSharingAllowed\": false\n"
      + "   },\n"
      + "   \"searchInfo\": {\n"
      + "    \"textSnippet\": \"Properties are a unique \\u003cb\\u003eAndroid\\u003c/b\\u003e feature we learned about in Chapter 3, \\u003cb\\u003eAndroid\\u003c/b\\u003e \\u003cbr\\u003e\\nIs Weird. We want to label ... However, instead of working on file paths, it works \\u003cbr\\u003e\\non property names or property \\u003cb\\u003ekeys\\u003c/b\\u003e (properties in \\u003cb\\u003eAndroid\\u003c/b\\u003e are a key-value store).\"\n"
      + "   }\n"
      + "  },\n"
      + "  {\n"
      + "   \"kind\": \"books#volume\",\n"
      + "   \"id\": \"ydwVQ4xX-4YC\",\n"
      + "   \"etag\": \"nuPYARaeLNM\",\n"
      + "   \"selfLink\": \"https://www.googleapis.com/books/v1/volumes/ydwVQ4xX-4YC\",\n"
      + "   \"volumeInfo\": {\n"
      + "    \"title\": \"Android: The Unofficial Handbook\",\n"
      + "    \"authors\": [\n"
      + "     \"Minute Help Guides Staff\"\n"
      + "    ],\n"
      + "    \"publisher\": \"Minute Help Press\",\n"
      + "    \"publishedDate\": \"2010-06-22\",\n"
      + "    \"industryIdentifiers\": [\n"
      + "     {\n"
      + "      \"type\": \"ISBN_13\",\n"
      + "      \"identifier\": \"9781610420792\"\n"
      + "     },\n"
      + "     {\n"
      + "      \"type\": \"ISBN_10\",\n"
      + "      \"identifier\": \"1610420799\"\n"
      + "     }\n"
      + "    ],\n"
      + "    \"readingModes\": {\n"
      + "     \"text\": true,\n"
      + "     \"image\": false\n"
      + "    },\n"
      + "    \"printType\": \"BOOK\",\n"
      + "    \"categories\": [\n"
      + "     \"Computers\"\n"
      + "    ],\n"
      + "    \"maturityRating\": \"NOT_MATURE\",\n"
      + "    \"allowAnonLogging\": true,\n"
      + "    \"contentVersion\": \"0.0.3.0.preview.2\",\n"
      + "    \"panelizationSummary\": {\n"
      + "     \"containsEpubBubbles\": false,\n"
      + "     \"containsImageBubbles\": false\n"
      + "    },\n"
      + "    \"imageLinks\": {\n"
      + "     \"smallThumbnail\": \"http://books.google.com/books/content?id=ydwVQ4xX-4YC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api\",\n"
      + "     \"thumbnail\": \"http://books.google.com/books/content?id=ydwVQ4xX-4YC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\"\n"
      + "    },\n"
      + "    \"language\": \"en\",\n"
      + "    \"previewLink\": \"http://books.google.ch/books?id=ydwVQ4xX-4YC&pg=PT16&dq=android:keyes&hl=&cd=8&source=gbs_api\",\n"
      + "    \"infoLink\": \"https://play.google.com/store/books/details?id=ydwVQ4xX-4YC&source=gbs_api\",\n"
      + "    \"canonicalVolumeLink\": \"https://market.android.com/details?id=book-ydwVQ4xX-4YC\"\n"
      + "   },\n"
      + "   \"saleInfo\": {\n"
      + "    \"country\": \"CH\",\n"
      + "    \"saleability\": \"FOR_SALE\",\n"
      + "    \"isEbook\": true,\n"
      + "    \"listPrice\": {\n"
      + "     \"amount\": 3.95,\n"
      + "     \"currencyCode\": \"CHF\"\n"
      + "    },\n"
      + "    \"retailPrice\": {\n"
      + "     \"amount\": 3.28,\n"
      + "     \"currencyCode\": \"CHF\"\n"
      + "    },\n"
      + "    \"buyLink\": \"https://play.google.com/store/books/details?id=ydwVQ4xX-4YC&rdid=book-ydwVQ4xX-4YC&rdot=1&source=gbs_api\",\n"
      + "    \"offers\": [\n"
      + "     {\n"
      + "      \"finskyOfferType\": 1,\n"
      + "      \"listPrice\": {\n"
      + "       \"amountInMicros\": 3950000.0,\n"
      + "       \"currencyCode\": \"CHF\"\n"
      + "      },\n"
      + "      \"retailPrice\": {\n"
      + "       \"amountInMicros\": 3280000.0,\n"
      + "       \"currencyCode\": \"CHF\"\n"
      + "      },\n"
      + "      \"giftable\": true\n"
      + "     }\n"
      + "    ]\n"
      + "   },\n"
      + "   \"accessInfo\": {\n"
      + "    \"country\": \"CH\",\n"
      + "    \"viewability\": \"PARTIAL\",\n"
      + "    \"embeddable\": true,\n"
      + "    \"publicDomain\": false,\n"
      + "    \"textToSpeechPermission\": \"ALLOWED\",\n"
      + "    \"epub\": {\n"
      + "     \"isAvailable\": true,\n"
      + "     \"acsTokenLink\": \"http://books.google.ch/books/download/Android_The_Unofficial_Handbook-sample-epub.acsm?id=ydwVQ4xX-4YC&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api\"\n"
      + "    },\n"
      + "    \"pdf\": {\n"
      + "     \"isAvailable\": false\n"
      + "    },\n"
      + "    \"webReaderLink\": \"http://play.google.com/books/reader?id=ydwVQ4xX-4YC&hl=&printsec=frontcover&source=gbs_api\",\n"
      + "    \"accessViewStatus\": \"SAMPLE\",\n"
      + "    \"quoteSharingAllowed\": false\n"
      + "   },\n"
      + "   \"searchInfo\": {\n"
      + "    \"textSnippet\": \"MENU + o: Zoom out · MENU + p: Go to Settings · SPACEBAR: Page down · \\u003cbr\\u003e\\nSHIFT + SPACEBAR: Page up Typing and Text Navigation \\u003cb\\u003eKeys\\u003c/b\\u003e · ALT + \\u003cbr\\u003e\\nSPACEBAR Insert special character · DEL Delete character to left · SHIFT + DEL \\u003cbr\\u003e\\nDelete&nbsp;...\"\n"
      + "   }\n"
      + "  },\n"
      + "  {\n"
      + "   \"kind\": \"books#volume\",\n"
      + "   \"id\": \"HauIAAAAQBAJ\",\n"
      + "   \"etag\": \"bTip9mZ8ngs\",\n"
      + "   \"selfLink\": \"https://www.googleapis.com/books/v1/volumes/HauIAAAAQBAJ\",\n"
      + "   \"volumeInfo\": {\n"
      + "    \"title\": \"Beginning Android C++ Game Development\",\n"
      + "    \"authors\": [\n"
      + "     \"Bruce Sutherland\"\n"
      + "    ],\n"
      + "    \"publisher\": \"Apress\",\n"
      + "    \"publishedDate\": \"2014-01-09\",\n"
      + "    \"description\": \"Beginning Android C++ Game Development introduces general and Android game developers like you to Android's powerful Native Development Kit (NDK). The Android NDK platform allows you to build the most sophisticated, complex and best performing game apps that leverage C++. In short, you learn to build professional looking and performing game apps like the book's case study, Droid Runner. In this book, you'll learn all the major aspects of game design and programming using the Android NDK and be ready to submit your first professional video game app to Google Play and Amazon Appstore for today's Android smartphones and tablet users to download and play. The techniques contained in this book include building a game engine, writing a renderer, and building a full game app with entities, game levels and collisions. As part of the tutorial you'll also learn about inserting perspectives using cameras and including audio in your game app.\",\n"
      + "    \"industryIdentifiers\": [\n"
      + "     {\n"
      + "      \"type\": \"ISBN_13\",\n"
      + "      \"identifier\": \"9781430258315\"\n"
      + "     },\n"
      + "     {\n"
      + "      \"type\": \"ISBN_10\",\n"
      + "      \"identifier\": \"1430258314\"\n"
      + "     }\n"
      + "    ],\n"
      + "    \"readingModes\": {\n"
      + "     \"text\": true,\n"
      + "     \"image\": true\n"
      + "    },\n"
      + "    \"pageCount\": 316,\n"
      + "    \"printType\": \"BOOK\",\n"
      + "    \"categories\": [\n"
      + "     \"Computers\"\n"
      + "    ],\n"
      + "    \"maturityRating\": \"NOT_MATURE\",\n"
      + "    \"allowAnonLogging\": true,\n"
      + "    \"contentVersion\": \"0.4.3.0.preview.3\",\n"
      + "    \"panelizationSummary\": {\n"
      + "     \"containsEpubBubbles\": false,\n"
      + "     \"containsImageBubbles\": false\n"
      + "    },\n"
      + "    \"imageLinks\": {\n"
      + "     \"smallThumbnail\": \"http://books.google.com/books/content?id=HauIAAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api\",\n"
      + "     \"thumbnail\": \"http://books.google.com/books/content?id=HauIAAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\"\n"
      + "    },\n"
      + "    \"language\": \"en\",\n"
      + "    \"previewLink\": \"http://books.google.ch/books?id=HauIAAAAQBAJ&pg=PA250&dq=android:keyes&hl=&cd=9&source=gbs_api\",\n"
      + "    \"infoLink\": \"https://play.google.com/store/books/details?id=HauIAAAAQBAJ&source=gbs_api\",\n"
      + "    \"canonicalVolumeLink\": \"https://market.android.com/details?id=book-HauIAAAAQBAJ\"\n"
      + "   },\n"
      + "   \"saleInfo\": {\n"
      + "    \"country\": \"CH\",\n"
      + "    \"saleability\": \"FOR_SALE\",\n"
      + "    \"isEbook\": true,\n"
      + "    \"listPrice\": {\n"
      + "     \"amount\": 45.5,\n"
      + "     \"currencyCode\": \"CHF\"\n"
      + "    },\n"
      + "    \"retailPrice\": {\n"
      + "     \"amount\": 31.85,\n"
      + "     \"currencyCode\": \"CHF\"\n"
      + "    },\n"
      + "    \"buyLink\": \"https://play.google.com/store/books/details?id=HauIAAAAQBAJ&rdid=book-HauIAAAAQBAJ&rdot=1&source=gbs_api\",\n"
      + "    \"offers\": [\n"
      + "     {\n"
      + "      \"finskyOfferType\": 1,\n"
      + "      \"listPrice\": {\n"
      + "       \"amountInMicros\": 4.55E7,\n"
      + "       \"currencyCode\": \"CHF\"\n"
      + "      },\n"
      + "      \"retailPrice\": {\n"
      + "       \"amountInMicros\": 3.185E7,\n"
      + "       \"currencyCode\": \"CHF\"\n"
      + "      },\n"
      + "      \"giftable\": true\n"
      + "     }\n"
      + "    ]\n"
      + "   },\n"
      + "   \"accessInfo\": {\n"
      + "    \"country\": \"CH\",\n"
      + "    \"viewability\": \"PARTIAL\",\n"
      + "    \"embeddable\": true,\n"
      + "    \"publicDomain\": false,\n"
      + "    \"textToSpeechPermission\": \"ALLOWED\",\n"
      + "    \"epub\": {\n"
      + "     \"isAvailable\": true,\n"
      + "     \"acsTokenLink\": \"http://books.google.ch/books/download/Beginning_Android_C++_Game_Development-sample-epub.acsm?id=HauIAAAAQBAJ&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api\"\n"
      + "    },\n"
      + "    \"pdf\": {\n"
      + "     \"isAvailable\": true,\n"
      + "     \"acsTokenLink\": \"http://books.google.ch/books/download/Beginning_Android_C++_Game_Development-sample-pdf.acsm?id=HauIAAAAQBAJ&format=pdf&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api\"\n"
      + "    },\n"
      + "    \"webReaderLink\": \"http://play.google.com/books/reader?id=HauIAAAAQBAJ&hl=&printsec=frontcover&source=gbs_api\",\n"
      + "    \"accessViewStatus\": \"SAMPLE\",\n"
      + "    \"quoteSharingAllowed\": false\n"
      + "   },\n"
      + "   \"searchInfo\": {\n"
      + "    \"textSnippet\": \"Private \\u003cb\\u003ekeys\\u003c/b\\u003e allow you to create encrypted messages or signatures which you \\u003cbr\\u003e\\ncan then share with others. The public key is a file which you can share with \\u003cbr\\u003e\\nothers to allow them to unecrypt this data. In the \\u003cb\\u003eAndroid\\u003c/b\\u003e ecosystem, the APKs&nbsp;...\"\n"
      + "   }\n"
      + "  },\n"
      + "  {\n"
      + "   \"kind\": \"books#volume\",\n"
      + "   \"id\": \"wnzBwNwMfGcC\",\n"
      + "   \"etag\": \"dQIesrlwTGw\",\n"
      + "   \"selfLink\": \"https://www.googleapis.com/books/v1/volumes/wnzBwNwMfGcC\",\n"
      + "   \"volumeInfo\": {\n"
      + "    \"title\": \"Pro Android Augmented Reality\",\n"
      + "    \"authors\": [\n"
      + "     \"Raghav Sood\"\n"
      + "    ],\n"
      + "    \"publisher\": \"Apress\",\n"
      + "    \"publishedDate\": \"2012-07-11\",\n"
      + "    \"description\": \"Augmented reality (AR) offers a live direct or indirect view of a physical, real-world environment, where the elements and surroundings are augmented by computer-generated sensory input such as graphics and GPS data. It makes a game more real. Your social media app puts you where want to be or go. Pro Android Augmented Reality walks you through the foundations of building an augmented reality application. From using various software and Android hardware sensors, such as an accelerometer or a magnetometer (compass), you'll learn the building blocks of augmented reality for both marker- and location-based apps. Case studies are included in this one-of-a-kind book, which pairs nicely with other Android development books. After reading Pro Android Augmented Reality, you'll be able to build augmented reality rich media apps or integrate all the best augmented reality into your favorite Android smartphone and/or tablet. What you’ll learn How to use most Android cameras How to find the user's location with GPS data How to detect movement and orientation of the device How to program against the accelerometer and compass How to use the AndAR library in marker recognition How to create an artificial horizon for your app How to integrate the Google Maps API into AR apps How to build enterprise augmented reality apps using the case studies in this book Who this book is for This book is for Android developers familiar with Android programming, but new to the camera, accelerometer, magnetometer and building augmented reality applications in general. Table of Contents Applications of Augmented Reality Basics of Augmented Reality on the Android Platform Adding Overlays Artificial Horizons Other Features of Augmented Reality A Simple App Using AR A More Complex Project Using More AR Features A Project Using All AR Features An AR Game\",\n"
      + "    \"industryIdentifiers\": [\n"
      + "     {\n"
      + "      \"type\": \"ISBN_13\",\n"
      + "      \"identifier\": \"9781430239451\"\n"
      + "     },\n"
      + "     {\n"
      + "      \"type\": \"ISBN_10\",\n"
      + "      \"identifier\": \"143023945X\"\n"
      + "     }\n"
      + "    ],\n"
      + "    \"readingModes\": {\n"
      + "     \"text\": true,\n"
      + "     \"image\": true\n"
      + "    },\n"
      + "    \"pageCount\": 346,\n"
      + "    \"printType\": \"BOOK\",\n"
      + "    \"categories\": [\n"
      + "     \"Computers\"\n"
      + "    ],\n"
      + "    \"maturityRating\": \"NOT_MATURE\",\n"
      + "    \"allowAnonLogging\": true,\n"
      + "    \"contentVersion\": \"preview-1.0.0\",\n"
      + "    \"panelizationSummary\": {\n"
      + "     \"containsEpubBubbles\": false,\n"
      + "     \"containsImageBubbles\": false\n"
      + "    },\n"
      + "    \"imageLinks\": {\n"
      + "     \"smallThumbnail\": \"http://books.google.com/books/content?id=wnzBwNwMfGcC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api\",\n"
      + "     \"thumbnail\": \"http://books.google.com/books/content?id=wnzBwNwMfGcC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\"\n"
      + "    },\n"
      + "    \"language\": \"en\",\n"
      + "    \"previewLink\": \"http://books.google.ch/books?id=wnzBwNwMfGcC&pg=PA117&dq=android:keyes&hl=&cd=10&source=gbs_api\",\n"
      + "    \"infoLink\": \"http://books.google.ch/books?id=wnzBwNwMfGcC&dq=android:keyes&hl=&source=gbs_api\",\n"
      + "    \"canonicalVolumeLink\": \"https://books.google.com/books/about/Pro_Android_Augmented_Reality.html?hl=&id=wnzBwNwMfGcC\"\n"
      + "   },\n"
      + "   \"saleInfo\": {\n"
      + "    \"country\": \"CH\",\n"
      + "    \"saleability\": \"NOT_FOR_SALE\",\n"
      + "    \"isEbook\": false\n"
      + "   },\n"
      + "   \"accessInfo\": {\n"
      + "    \"country\": \"CH\",\n"
      + "    \"viewability\": \"PARTIAL\",\n"
      + "    \"embeddable\": true,\n"
      + "    \"publicDomain\": false,\n"
      + "    \"textToSpeechPermission\": \"ALLOWED\",\n"
      + "    \"epub\": {\n"
      + "     \"isAvailable\": true,\n"
      + "     \"acsTokenLink\": \"http://books.google.ch/books/download/Pro_Android_Augmented_Reality-sample-epub.acsm?id=wnzBwNwMfGcC&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api\"\n"
      + "    },\n"
      + "    \"pdf\": {\n"
      + "     \"isAvailable\": true,\n"
      + "     \"acsTokenLink\": \"http://books.google.ch/books/download/Pro_Android_Augmented_Reality-sample-pdf.acsm?id=wnzBwNwMfGcC&format=pdf&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api\"\n"
      + "    },\n"
      + "    \"webReaderLink\": \"http://play.google.com/books/reader?id=wnzBwNwMfGcC&hl=&printsec=frontcover&source=gbs_api\",\n"
      + "    \"accessViewStatus\": \"SAMPLE\",\n"
      + "    \"quoteSharingAllowed\": false\n"
      + "   },\n"
      + "   \"searchInfo\": {\n"
      + "    \"textSnippet\": \"&lt;LinearLayout xmlns:\\u003cb\\u003eandroid\\u003c/b\\u003e=&quot;http://schemas.\\u003cb\\u003eandroid\\u003c/b\\u003e.com/apk/res/\\u003cb\\u003eandroid\\u003c/b\\u003e&quot; \\u003cbr\\u003e\\n\\u003cb\\u003eandroid\\u003c/b\\u003e:layout_width=&quot;fill_parent&quot; ... Therefore, if you plan to publish your \\u003cbr\\u003e\\napplication, you have to generate two API \\u003cb\\u003ekeys\\u003c/b\\u003e: one for your debug certificate (\\u003cbr\\u003e\\nthe one&nbsp;...\"\n"
      + "   }\n"
      + "  }\n"
      + " ]\n"
      + "}\n";

  @Test
  public void checkParseOfBookList(){
    List<Book> books = new ArrayList<Book>();
    for (int i = 0; i <10; i++) {
      books.add(new Book());
    }
    BookList bookList = new BookList(books);

    Gson gson = new Gson(); // Or use new GsonBuilder().create();
    BookList resultBookList = gson.fromJson(jsonResponse,BookList.class);
    assertNotNull(resultBookList);
    assertTrue(bookList.getBooks().size() == resultBookList.getBooks().size());
  }

}
